// ─────────────────────────────────────────────────────────────────────────────
// API layer — wraps all backend calls.
// When VITE_USE_MOCK_DATA=true, returns local mock data instantly.
// ─────────────────────────────────────────────────────────────────────────────

import {
  MOCK_CITIES,
  MOCK_EMISSIONS,
  getMockRecommendations,
} from '@/data/mockData';

const USE_MOCK = import.meta.env.VITE_USE_MOCK_DATA === 'true';
const BASE = import.meta.env.VITE_API_URL || '/v1';

// Simulate a short async delay for mock data to mimic real API feel
const delay = (ms = 200) => new Promise(r => setTimeout(r, ms));

async function apiFetch(path, options = {}) {
  const url = `${BASE}${path}`;
  const res = await fetch(url, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
  });
  if (!res.ok) {
    const error = await res.text().catch(() => res.statusText);
    throw new Error(`API ${res.status}: ${error}`);
  }
  return res.json();
}

// ── Cities ────────────────────────────────────────────────────────────────────

export async function getCities() {
  if (USE_MOCK) {
    await delay(150);
    return MOCK_CITIES.map(c => ({
      city_id: c.city_id,
      name: c.name,
      state: c.state,
      lat: c.lat,
      lng: c.lng,
      total_co2e_mt: c.total_co2e_mt,
      co2e_per_capita: c.co2e_per_capita,
      has_bps: c.has_bps,
      trend_yoy: c.trend_yoy,
    }));
  }
  return apiFetch('/cities');
}

export async function getCity(cityId) {
  if (USE_MOCK) {
    await delay(180);
    const city = MOCK_CITIES.find(c => c.city_id === cityId);
    if (!city) throw new Error(`City not found: ${cityId}`);
    return city;
  }
  return apiFetch(`/cities/${cityId}`);
}

// ── Emissions ─────────────────────────────────────────────────────────────────

export async function getEmissionsSummary(cityId) {
  if (USE_MOCK) {
    await delay(160);
    const data = MOCK_EMISSIONS[cityId];
    if (!data) throw new Error(`Emissions data not found: ${cityId}`);
    return data;
  }
  return apiFetch(`/emissions/${cityId}/summary`);
}

// ── AI / RAG ──────────────────────────────────────────────────────────────────

export async function askQuestion(query, cityId) {
  if (USE_MOCK) {
    await delay(1800); // simulate LLM latency
    return {
      answer: `**Mock AI Response** — This is a placeholder response for: "${query}"\n\nIn production, this would be a grounded answer retrieved via RAG from the CarbonLens document corpus (NYC LL97, EPA data, NREL reports) and generated by Claude 3.5 Sonnet.\n\nEnable the backend (FastAPI + ChromaDB) and set VITE_USE_MOCK_DATA=false to get real AI responses with citations.`,
      confidence: 'medium',
      sources: [
        { name: 'Climate TRACE 2024', relevance: 0.91 },
        { name: 'EPA GHGRP', relevance: 0.85 },
      ],
      time_ms: 1823,
    };
  }
  return apiFetch('/ask', {
    method: 'POST',
    body: JSON.stringify({ query, city_id: cityId }),
  });
}

// ── Recommendations ───────────────────────────────────────────────────────────

export async function getRecommendations(cityId) {
  if (USE_MOCK) {
    await delay(120);
    const data = getMockRecommendations(cityId);
    if (!data) throw new Error(`Recommendations not found: ${cityId}`);
    return data;
  }
  return apiFetch(`/recommendations/${cityId}`);
}

// ── Compare ───────────────────────────────────────────────────────────────────

export async function compareCities(cityIds) {
  if (USE_MOCK) {
    await delay(180);
    return {
      cities: MOCK_CITIES.filter(c => cityIds.includes(c.city_id)).map(c => ({
        city_id: c.city_id,
        name: c.name,
        state: c.state,
        total_co2e_mt: c.total_co2e_mt,
        co2e_per_capita: c.co2e_per_capita,
        has_bps: c.has_bps,
        trend_yoy: c.trend_yoy,
        solar_ghi: c.renewables?.solar_ghi,
        grid_renewable_pct: c.grid?.renewable_pct,
        bps_name: c.bps?.name || null,
        population: c.population,
      })),
    };
  }
  return apiFetch(`/compare?cities=${cityIds.join(',')}`);
}
